stages:
  - build

.build:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq git-core
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
  script: .industrial_ci/gitlab.sh
  services: []
  variables:
    ISOLATION: shell
    NOT_TEST_BUILD: 'true'
  tags:
    - asprunner

humble:
  extends: [.build]
  image: ros:humble

iron:
  extends: [.build]
  image: ros:iron

rolling:
  extends: [.build]
  image: ros:rolling