header_guard: GENERATED_DATATYPES_HPP
variable1:
  description: "This is a description"
  type: struct
  typeID: "{1, 1}" # example
  bynaryTypeID: "{1, 4023 }" # example
  elements:
    - { type: int, name: name } # datatype and names
    - { type: bool, name: name1 }

variable2:
  description: "This is a description"
  type: struct
  typeID: "{1, 2}" # example
  bynaryTypeID: "{1, 4024 }" # example
  elements:
    - { type: int, name: name } # datatype and names
    - { type: bool, name: name1 }
