variable1: 
  type: struct
  typeID: {1, 1} # example
  bynaryTypeID: {1, 4023 } # example
  elements: 
    - { type: int, name: hello } # datatype and names
    - { type: bool, name: hello1 } # datatype and names