name: Pre-Commit Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.1
    - name: Install system hooks
      run: sudo apt install -qq clang-format-14 cppcheck
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --hook-stage manual